apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: 863518836478-dev-kf13-12-pipelines
      keyPrefix: pipelines/artifacts
      endpoint: s3.amazonaws.com
      region: eu-west-1
      insecure: false
      accessKeySecret:
        name: pipelines-s3-secret 
        key: S3_ACCESSKEY
      secretKeySecret: 
        name: pipelines-s3-secret
        key: S3_SECRETKEY
