apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::863518836478:role/dev-kf13-3_kubeflow
  data:
    - key: <<__external_secret_name.kubeflow.s3_accesskey__>>
      name: S3_ACCESSKEY
    - key: <<__external_secret_name.kubeflow.s3_secretkey__>>
      name: S3_SECRETKEY
