apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::161747956760:role/eksctl-ml-cluster-ServiceRole-HKNXG6ZC03XD
  labels:
    name: kubernetes-external-secrets
