apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: lars@aflorithmic.ai
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z01884081A34VMRZ2H6J9
          region: eu-west-1
          # role: <<__role_arn.cert_manager__>>
