apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-kubeflow-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aflorithmic/argoflow-aws.git
    targetRevision: v0.3
    path: distribution/kubeflow/istio-kubeflow-resources
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
