kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: dev-kf13-3-instance.c6e2xeayekua.eu-central-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: <<__s3.bucket.mlflow__>>
  ARTIFACT_S3_KEY_PREFIX: <<__s3.key_prefix.mlflow__>>
