apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-viewer-template
data:
  viewer-tensorboard-template.json: |
    {
        "metadata": {
            "annotations": {
                "eks.amazonaws.com/role-arn": "arn:aws:iam::161747956760:role/eksctl-ml-cluster-ServiceRole-HKNXG6ZC03XD"
            }
        },
        "spec": {
            "containers": [
                {
                    "env": [
                        {
                            "name": "AWS_REGION",
                            "value": "eu-west-1"
                        }
                    ]
                }
            ]
        }
    }