apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      securityContext:
        fsGroup: 65534
      containers:
      - name: external-dns
        image: docker.io/bitnami/external-dns:0.7.6-debian-10-r91
        env:
        - name: AWS_REGION
          value: eu-west-1
        args:
          - --source=service
          - --source=ingress
          - --domain-filter=platform.aflr.io
          - --provider=aws
          - --policy=upsert-only
          - --aws-zone-type=public
          - --aws-assume-role=arn:aws:iam::161747956760:role/eksctl-ml-cluster-ServiceRole-HKNXG6ZC03XD
          - --registry=txt
          - --txt-owner-id=ml
