apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::863518836478:role/dev-kf13-3_argocd
  data:
    - key: dev-kf13-3/argocd/https_username
      name: HTTPS_USERNAME
    - key: dev-kf13-3/argocd/https_password
      name: HTTPS_PASSWORD
