apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  tag: 1.9.5 # istio/operator
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: proxy_protocol_v2.enabled=true
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 2 } }'
          external-dns.alpha.kubernetes.io/hostname: kubeflow.platform.aflr.io, auth.platform.aflr.io, serving.platform.aflr.io, *.serving.platform.aflr.io
