apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
- ../base
- secret.yaml
- virtualservice.yaml

patchesStrategicMerge:
- patches/service.yaml

configMapGenerator:
- name: oidc-authservice-parameters
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true
