kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBfwCqUr/FOIcTGkytnTKHff+NZ97iAoocNQ0yOrVjrUg1k6SxfxhbnKUa3g8KtXZ+5pxA0yoZMmWlWCMHV+Bn5h+0qAtJM2TpLrmGUCvOEyC52qhDFAxm6Zx1xGuniAZyWHyFp4wflMEG0S3/lD7JTFiox/zXVCwTz81ueFchYCffUVBXxfBDjW6an088RxYhk2Nxt/veQ7P4a2R7f5AWXSqrIGEHvm3fIe+64K11xnknNkpyjxJu29O5XnxOCrAFo8kWB4qT4Pj1NpXEwY61S3Xuq/XDAb7v7zZrIppPRFdz+WUfxAKhNfnvOtfltefpn86pJ6DgcRvYV4teMY+n3UDHanKUFy73LyXT3o7Lb/ldweHmzftZLRB+I3e9/rXU3S9Z20nDjPeMZzw2P2vsU4lZFkN6WTCp6x2pJ3obRbKIC+VOcRwE0/UsNAQps/vIQ0yT88NijN5JcLbf0RZ7f7HZ/mCS26WGcwwOr/48NWIKHubuRROFD28WdCXzx3sWJxyBJ3ol/OE/opt/aciezcmIZpvsFcsg3kxeB+9Q+jyH810vp+uILT51XXt5XTycC4V5DYBbuAbwL2xZ5Rd9OUQVQprllXLadFXk/d6ew5xjRsTfsQPErwYl71QeKQf+oB5aKXM7QgMuuC5+x7NiIQkH2hJQ1R+Otzfu8ekBDYCHZFtWRx8TXH6LebhF0vuPpqKqSCYOWR9daebDxey2i
    admin-user: AgC/u9M6kk1MVqzo8dVTAZNELI6yK+vZiXTDwA8ROoYJ3SJk0BUqa4qdgzdlPG7QbH36N62TQlHpZtcyQzdyqdXtxARej8ekor+qheCJ+aIdX4mwCjtspB7KKH4P4JEboqkEAl/sGt46yL5Rc0OEJwDbGmxS7fHnsEJ6r8HtDEOY8/NZXNDgfaVtm3JC7C0ezV5xKOUwkQWjhIfA838Vbt2FAWYwOP//Pcfri2qspXURASgR0t/1JiOD+9lT9vYvNajt2fR+y7LlZyUiVOLT+5LMuzkoRoJAiMidH8ZDB4OTekeXyyOlHUlEllQmKlwlATwExZuXqzwzZfeW9/5xyz3y8Otj9yyaa1BkdX7KOeHBrriqxw/qwsFev5KZ4th6nM2pNmbTPbTTc1NfVXhqGYPyxDJ77hAYFpKOOcfcfCCY9gaIlBiFRtj4Pil+xKnZ+NdIZeGdZl/YTywZwaLPPFGQ8+wGdORIUyYeWcNcswVSREX4NUvZTfobk9FMbchl964e78oyAa/unOGQCxQQJ4lbYLc3sIaUwRe1sG2OwShireYO2RySSdHReKv03dN2OqOOWs+nMhSXxuJ9nxYko//9/UWsRYentecwjaKWCgmCOeTeCmqpChpQboT9StDvtuPfa923J9vOVSksziBM59rarTtHMC7EK/5/8uxEZeRfNeS9wRRW2gxZf4WG5+SlP9qObRHa
